# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e45e52104be9f053e1904a1e253c7f39175bf186e87c56d00a371784b929a195045ebdea1779e2480e36dd4ebaf7923a9da498f2c7579bf1e76baf850a9b737b

test:
  secret_key_base: b8c6183df6ae3197d76287e25ab29b75cff9e0a909a9d4c8c220fd9772c6a4765b42bd97c4e7c2cae2d194e62a52270030398660d25e9900fb7f1b2b8ab5748d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
